### ISSUE TITLE
Issue installing Moltiverse from Curl

### ISSUE THREAD

**Issue by LucianoPenaTejo** [ucm-lbqc/moltiverse#6]
**Using the quick install you receive the following error:** 
...
Installing hclust (1.0.0 at e00db0b)
Writing shard.lock
Building: moltiverse
Error target moltiverse failed to compile:
/usr/bin/ld: no se puede encontrar -lyaml: No existe el archivo o el directorio
collect2: error: ld returned 1 exit status
**Error**: execution of command failed with exit status 1: cc "${@}" -o /home/luciano/moltiverse/bin/moltiverse  -rdynamic -L/opt/crystal-1.13.1-1/bin/../lib/crystal -lyaml -lpcre2-8 -lm -lgc -lpthread -levent -lrt -lpthread -ldl

To overcome this issue, just install libyaml. In my case I use ubuntu22.04: 
`sudo apt install libyaml-dev
`

**Comment by maurobedoya** [comment]
Thanks @LucianoPenaTejo  for spotting this bug!.
For now, we have added a simple solution which consists of checking if `libyaml` is installed and if it is not installed the command `sudo apt-get install libyaml-dev` will be used. Probably in the future release we will check it in another way.

The commits 2edad86 a50b128 solved the issue.
