### ISSUE TITLE
Problems installing moltiverse via curl in mac os

### ISSUE THREAD

**Issue by vrojas22** [ucm-lbqc/moltiverse#7]
When trying to perform the quick installation of multiverse the following error appears in mac os.

$ curl -fsSL https://raw.githubusercontent.com/ucm-lbqc/moltiverse/master/INSTALL.sh | bash
Checking system dependencies...
Checking for libyaml-dev...
bash: line 27: ldconfig: command not found
libyaml-dev is not installed.
sudo: apt-get: command not found

**Comment by maurobedoya** [comment]
Thank you for reporting this issue.
The current version of Moltiverse has only been tested on Linux-based systems, including Windows Subsystem for Linux (WSL) for Windows users. We have not yet tested compatibility with macOS. We will prioritize macOS support in future developments.
